- hosts: localhost

  tasks:
    - name: pull imagem do docker
      docker_image:
        name: wellbastos/python-flask-web:latest
        #        source: pull

    - name: run docker image
      docker_container:
        name: python-flask-web
        image: wellbastos/python-flask-web:latest
        state: started
        ports:
         - "5000:5000"

