- hosts: localhost

  tasks:
    - name: create directory for build
      file:
        path: /app
        state: directory

    - name: clonning the application repository
      git:
        repo: https://github.com/wellbastos/python-flask-web.git
        dest: /app
        version: master

    - name: building docker image
      docker_image:
        name: wellbastos/python-flask
        path: /app
        state: build
        force: yes      

    - name: stop running container
      docker_container:
        name: python-flask      
        state: stopped

    - name: run docker image
      docker_container:
        name: python-flask
        image: wellbastos/python-flask:latest
        state: started
        ports: 
         - "5000:5000"

    - name: push docker image to docker hub
      docker_image:
        name: wellbastos/python-flask:latest
        repository: wellbastos/python-flask
        tag: latest
        push: yes